# Generated by Django 3.1.3 on 2021-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_auto_20210124_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
