# Generated by Django 3.1.3 on 2021-01-22 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20210103_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='topic',
            name='data_create',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
