# Generated by Django 3.1.3 on 2021-01-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_auto_20210123_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['data_create']},
        ),
    ]
