# Generated by Django 3.1.3 on 2021-01-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_auto_20210123_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
