# Generated by Django 3.1.3 on 2021-01-23 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_auto_20210123_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 12, 9, 50, 617065)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 12, 9, 50, 617065)),
        ),
    ]
