# Generated by Django 3.1.3 on 2021-01-24 00:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_auto_20210123_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 12, 25, 29, 879162)),
        ),
    ]
